### ISSUE TITLE
Arch Linux: Google Chrome not working with xdg-gmail.

### ISSUE THREAD

**Issue by f3bruary** [mbr/xdg-gmail#1]
Hi,

I'm using Arch Linux and this script won't work for me. I checked out the python script and noticed you check for the existence of 'google-chrome' and 'chromium-browser'.

Many package managers install Google Chrome as google-chrome-stable however. I changed it locally and now the script works.

I still can't get google-chrome-stable to open gmail when I click a mailto link though. It keeps opening in Firefox. My ~/.local/share/applications/mimeapps.list has "x-scheme-handler/mailto=xdg-gmail.desktop" in it and I executed "sudo update-desktop-database -q" like the installation script said.

Source: https://aur.archlinux.org/packages/xdg-gmail-git/

**Comment by mbr** [comment]
I wasn't aware the script made it into arch. That's a bit scary, especially considering the script at https://aur.archlinux.org/packages/xd/xdg-gmail-git/PKGBUILD

It also does not seem to install the icons?

As for the `google-chrome` issue, it is available on all debian systems, in /etc/alternatives, pointing to one of the chrome channels. I'll write a fix.

**Comment by mbr** [comment]
As for you mimeapps troubles, here are some ideas: http://www.fvwmforums.org/phpBB3/viewtopic.php?f=43&t=2978

**Comment by f3bruary** [comment]
Fixed by adding a handler manually in Google Chome from the Gmail page. Unrelated to this xdg-gmail I suppose.
